# Health Check
GET http://localhost:3000/health_check
Content-Type: application/json
###

# Register Account
POST http://localhost:3000/registrations
Content-Type: application/json

{
  "account": {
    "email": "pedro23@mail.com",
    "password": "passworD123",
    "password_confirmation": "passworD123"
  }
}
