default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USER", "pedro") %>
  password: <%= ENV.fetch("DB_PASS", "password") %>

development:
  <<: *default
  database: api_with_auth_boilerplate_development

test:
  <<: *default
  database: api_with_auth_boilerplate_test

production:
  <<: *default
  database: api_with_auth_boilerplate_production
